name: CI/CD for Next.js

on:
  push:
    branches:
      - main  # Adjust the branch as needed
      - feature/add-pipeline

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install Netlify
        run:  npm install -g netlify-cli
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Netlify Login
        run: netlify login --token ${{ secrets.NETLIFY_API_TOKEN }}
      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify --version
          echo "Deploying to production. Site ID: $NETLIFY_SITE_ID" 
          netlify status
          netlify deploy --dir=out --prod --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --site=${{ secrets.NETLIFY_SITE_ID }}

