name: CI/CD for Next.js

on:
  push:
    branches:
      - main  # Adjust as needed
      - feature/add-pipeline

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      # Ensure the correct build output directory is specified
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      # Use the `netlify deploy` command directly for authentication
      - name: Deploy to Netlify
        run: |
          echo "Deploying to production. Site ID: ${{ secrets.NETLIFY_SITE_ID }}"
          netlify deploy --prod --dir=out --auth=${{ secrets.NETLIFY_API_TOKEN }} --site=${{ secrets.NETLIFY_SITE_ID }}
